CREATE TABLE users(
	id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(65) NOT NULL,
    full_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE
);


CREATE TABLE books(
	id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    status ENUM('READING','COMPLETED','BUCKET_LIST','CREATED') NOT NULL,
    rating FLOAT DEFAULT NULL, CHECK (rating <= 5.00),
    pages INT NOT NULL,
    description VARCHAR(512) DEFAULT NULL,
    thumbnail_url VARCHAR(512) DEFAULT NULL,
    started_at TIMESTAMP DEFAULT NULL,
    completed_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_At TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_At TIMESTAMP DEFAULT NULL,
    
    CONSTRAINT UNIQUE_USER_BOOK_TITLE UNIQUE (user_id, title),
    -- foreign key constraint
    CONSTRAINT FK_USER_BOOK FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE tags(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE books_tags(
	book_id INT NOT NULL,
    tag_id INT NOT NULL,
    
    -- foreign key constraints
    CONSTRAINT FK_BOOK_TAG FOREIGN KEY(book_id) REFERENCES books(id),
    CONSTRAINT FK_TAG_BOOK FOREIGN KEY(tag_id) REFERENCES tags(id),
    
    PRIMARY KEY(book_id, tag_id)
);

CREATE TABLE book_status_history(
	id INT PRIMARY KEY AUTO_INCREMENT,
    book_id INT NOT NULL,
    old_status ENUM('READING','COMPLETED','BUCKET_LIST','CREATED') NOT NULL,
    new_status ENUM('READING','COMPLETED','BUCKET_LIST','CREATED') NOT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    -- foreign key constraint
    CONSTRAINT FK_HISTORY_BOOK FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE TABLE blacklisted_tokens
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(600) NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT token UNIQUE(token)
);
